-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 08:12:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema platform
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema platform
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `platform` DEFAULT CHARACTER SET utf8 ;
USE `platform` ;

-- -----------------------------------------------------
-- Table `platform`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `userToSupplier_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `userToSupplier`
    FOREIGN KEY (`user_id`)
    REFERENCES `platform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `UserToAdmin_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `UserToAdmin`
    FOREIGN KEY (`user_id`)
    REFERENCES `platform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`pharmancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`pharmancy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `userToPharmacy_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `userToPharmacy`
    FOREIGN KEY (`user_id`)
    REFERENCES `platform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`product_refrance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`product_refrance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_en` VARCHAR(255) NOT NULL,
  `name_ar` VARCHAR(255) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `product_refrance_id` INT NOT NULL,
  PRIMARY KEY (`id`, `supplier_id`, `product_refrance_id`),
  INDEX `productRefranceProduct_idx` (`product_refrance_id` ASC) VISIBLE,
  INDEX `supplierProduct_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `productRefranceProduct`
    FOREIGN KEY (`product_refrance_id`)
    REFERENCES `platform`.`product_refrance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supplierProduct`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `platform`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`supplier_pharmancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`supplier_pharmancy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `pharmacy_id` INT NOT NULL,
  `code` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `supplier_id`, `pharmacy_id`),
  INDEX `supplierSupplierPharmancy_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `pharmancySupplierPharmancy_idx` (`pharmacy_id` ASC) VISIBLE,
  CONSTRAINT `supplierSupplierPharmancy`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `platform`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pharmancySupplierPharmancy`
    FOREIGN KEY (`pharmacy_id`)
    REFERENCES `platform`.`pharmancy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DOUBLE NOT NULL,
  `pharmacy_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pharmacy_id`),
  INDEX `pharamcy` () VISIBLE,
  INDEX `pharmacyCart_idx` (`pharmacy_id` ASC) VISIBLE,
  CONSTRAINT `pharmacyCart`
    FOREIGN KEY (`pharmacy_id`)
    REFERENCES `platform`.`pharmancy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`cart_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `qty` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`, `cart_id`, `product_id`),
  INDEX `cartCartItem_idx` (`cart_id` ASC) VISIBLE,
  INDEX `produt_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `cartCartItem`
    FOREIGN KEY (`cart_id`)
    REFERENCES `platform`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produt`
    FOREIGN KEY (`product_id`)
    REFERENCES `platform`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `platform`.`cartStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `platform`.`cartStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cart_id`, `user_id`),
  INDEX `statusToCart_idx` (`cart_id` ASC) VISIBLE,
  INDEX `userToCart_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `statusToCart`
    FOREIGN KEY (`cart_id`)
    REFERENCES `platform`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userToCart`
    FOREIGN KEY (`user_id`)
    REFERENCES `platform`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
